### ISSUE TITLE
Does any of this functionality still work in FreeCAD ?

### ISSUE THREAD

**Issue by luzpaz** [marmei/FreeCADBiotSavart#1]

**Comment by marmei** [comment]
No I do not think it works any more - since a lot has changed in FreecCAD... Also with python 3 it will not work since blitz is obsolete. If you are interested - I can send you the new solver.

**Comment by luzpaz** [comment]
@marmei yes please

**Comment by marmei** [comment]
Hi @luzpaz, the solver is now on  https://github.com/marmei/nmrgrad.git
Many greetings
